In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from pandasql import sqldf

ModuleNotFoundError: No module named 'pandasql'

#### Read First File

In [4]:
df_1 = pd.read_csv(r"C:\Users\Ayobami Adeyemo\Downloads\project_notion\task-1-20260530T065100Z-3-001\task-1\radio.csv")
df_1.head()

                              Title     Imp's
0                   Ijo (Laba Laba)  53595389
1  Certified Loner (No Competition)  52281640
2          Peace Be Unto You (PBUY)  51681908
3                        Girlfriend  50647245
4                           Bandana  49512679

In [5]:
df_1.shape

(325, 2)

In [13]:
df_1['Title'].value_counts()

Title
Ijo (Laba Laba)                     1
Certified Loner (No Competition)    1
Peace Be Unto You (PBUY)            1
Girlfriend                          1
Bandana                             1
                                   ..
Loading                             1
i                                   1
never forget                        1
Way Too Big                         1
Toni-Ann Singh                      1
Name: count, Length: 325, dtype: int64

In [14]:
df_1['Title'].duplicated().sum()

np.int64(0)

In [15]:
df_1['Title'].is_unique

True

In [16]:
df_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Title   325 non-null    str
 1   Imp's   325 non-null    int64
dtypes: int64(1), str(1)
memory usage: 5.2 KB

In [17]:
df_1.describe()

              Imp's
count  3.250000e+02
mean   6.410955e+06
std    9.385881e+06
min    6.617000e+05
25%    1.931617e+06
50%    3.058215e+06
75%    6.076546e+06
max    5.359539e+07